### ISSUE TITLE
There is a question about installing smiles-featurizers

### ISSUE THREAD

**Issue by Tian1225** [MoleculeTransformers/smiles-featurizers#1]
Building wheels for collected packages: cryptacular
  Building wheel for cryptacular (pyproject.toml) ... done
  WARNING: Building wheel for cryptacular failed: [Errno 2] No such file or directory: 'C:\\Users\\Tian\\AppData\\Local\\Temp\\pip-wheel-w0skx4fb\\cryptacular-1.6.2-cp38-cp38-win_amd64.whl'
Failed to build cryptacular
ERROR: Could not build wheels for cryptacular, which is required to install pyproject.toml-based projects.

So how to fix it?

**Comment by shahrukhx01** [comment]
Hi @Tian1225, Maybe the following Stackoverflow thread could be useful here:

[https://stackoverflow.com/questions/56127273/failing-to-pip3-install-apex-down-to-failure-to-build-cryptacular-installed](https://stackoverflow.com/questions/56127273/failing-to-pip3-install-apex-down-to-failure-to-build-cryptacular-installed)

Please let me know if this resolves the issue for you.

**Comment by Tian1225** [comment]
Thanks for your answer！But,there is a new problem in use.

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 
I have update the protoc and downgrade the protobuf package, the TypeError still exitence.

**Comment by shahrukhx01** [comment]
You were only required to only downgrade the version of `protobuf` that might have been enough.

Additionally, if the local environment still does not work for you can also try `smiles-featurizes` on a [colab notebook here.](https://colab.research.google.com/drive/1wwEy06iqvOznnnep56SgznqkeEHDQOoD?usp=sharing)

**Comment by Tian1225** [comment]
I have fixed the problem. Thank you!

**Comment by shahrukhx01** [comment]
@Tian1225 Could you please state your solution for future users?

**Comment by Tian1225** [comment]
When using pip in anaconda to install smiles-featurizers in a virtual environment, the following error occurs:

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 
When using pip in anaconda to install smiles-featurizers in a virtual environment, the following error occurs:
First you need to uninstall protobuf (pip uninstall protobuf)
Then install protobuf==3.19.0 (pip install protobuf==3.19.0)
If there is an error about the channel in the above method, you can use conda to install protobuf==3.19.0 (conda install protobuf==3.19.0)
Hope this helps future users who encounter such problems.

**Comment by jlinghu** [comment]
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython>=2.1.0->mlflow<=1.13.1->farm==0.8.0->smiles-featurizers==1.0.8)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6d/01/7caa71608bc29952ae09b0be63a539e50d2484bc37747797a66a60679856/smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.1.4->azure-storage-blob>=12.0.0->mlflow<=1.13.1->farm==0.8.0->smiles-featurizers==1.0.8) (2.21)
Building wheels for collected packages: cryptacular
  Building wheel for cryptacular (pyproject.toml) ... done
  WARNING: Building wheel for cryptacular failed: [Errno 2] No such file or directory: '/tmp/pip-wheel-ndegd3hy/cryptacular-1.6.2-cp38-cp38-linux_x86_64.whl'
Failed to build cryptacular
ERROR: Could not build wheels for cryptacular, which is required to install pyproject.toml-based projects
I have this problem,I can't solve it with above way

**Comment by shahrukhx01** [comment]
@jlinghu are you still having this issue? If yes, please feel free to open a new issue. Thanks :)
