### ISSUE TITLE
smiles-featurizers gone?

### ISSUE THREAD

**Issue by Tian1225** [MoleculeTransformers/smiles-featurizers#2]
Excuse me, why aren't smiles-featurizers working? The link to "Hugging Face" went missing.

**Comment by shahrukh-ix** [comment]
Hi @Tian1225, Thank you for actively using `smiles-featurizers`. Hugging Face is experiencing an outage. I believe the models will become available once again once the HF outage gets resolved.

Here's the update:
https://twitter.com/huggingface/status/1655885897961811971

**Comment by Tian1225** [comment]
Thanks for your answer. I'll wait for Hugging Face to sort things out. Hope smiles-featurizers can be used soon.

**Comment by shahrukhx01** [comment]
@Tian1225  the models are available now.

**Comment by Tian1225** [comment]
OK！I am utilizing it now.
